[package]
name = "rainbow"
version = "0.1.0"
authors = ["archification <archification@gmail.com>"]
edition = "2024"

[profile.release]
strip = true
lto = true
codegen-units = 1
panic = "abort"

[dependencies]
crossterm = "0.28.1"
rand = "0.9.0"
